FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /enigma_app

COPY ./enigma_app /enigma_app
COPY requirements.txt /enigma_app/requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "enigma_app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]